name: ${name}
version: ${version}
description: Displays messages on player login
author: acomputerdog
website: https://github.com/AcomputerdogMC/Motds
main: net.acomputerdog.motd.PluginMOTD

commands:
  motd:
    description: Display all motds
    permission: motd.command
    aliases: [motds, showmotd, showmotds]
  reloadmotd:
    description: Reload the plugin (and MOTDs)
    permission: motd.reload
    aliases: [motdreload, reloadmotds, motdsreload]

permissions:
  motd.command:
    description: Allow use of /motd
    default: true
  motd.reload:
    description: Allow use of /reloadmotd
    default: op
